CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_roles_name CHECK (name IN ('ADMIN', 'LANDLORD', 'TENANT'))
);

CREATE TABLE user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    phone VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_user_accounts_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED'))
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE RESTRICT,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    landlord_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE RESTRICT,
    name VARCHAR(150) NOT NULL,
    address_line VARCHAR(255) NOT NULL,
    ward VARCHAR(100),
    district VARCHAR(100),
    province_city VARCHAR(100) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_properties_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE RESTRICT,
    room_number VARCHAR(50) NOT NULL,
    floor_number INTEGER,
    area NUMERIC(8, 2) NOT NULL,
    monthly_rent NUMERIC(15, 2) NOT NULL,
    default_deposit NUMERIC(15, 2) NOT NULL DEFAULT 0,
    max_occupants SMALLINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_rooms_area CHECK (area > 0),
    CONSTRAINT ck_rooms_monthly_rent CHECK (monthly_rent >= 0),
    CONSTRAINT ck_rooms_default_deposit CHECK (default_deposit >= 0),
    CONSTRAINT ck_rooms_max_occupants CHECK (max_occupants > 0),
    CONSTRAINT ck_rooms_status CHECK (status IN ('AVAILABLE', 'OCCUPIED', 'MAINTENANCE', 'INACTIVE'))
);

CREATE TABLE tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    landlord_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE RESTRICT,
    user_account_id BIGINT UNIQUE REFERENCES user_accounts(id) ON DELETE RESTRICT,
    full_name VARCHAR(150) NOT NULL,
    date_of_birth DATE,
    phone VARCHAR(20),
    email VARCHAR(255),
    identity_number VARCHAR(50),
    permanent_address TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_tenants_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE rental_contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE RESTRICT,
    contract_code VARCHAR(50) NOT NULL UNIQUE,
    start_date DATE NOT NULL,
    end_date DATE,
    monthly_rent NUMERIC(15, 2) NOT NULL,
    deposit_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_rental_contracts_dates CHECK (end_date IS NULL OR end_date > start_date),
    CONSTRAINT ck_rental_contracts_monthly_rent CHECK (monthly_rent >= 0),
    CONSTRAINT ck_rental_contracts_deposit CHECK (deposit_amount >= 0),
    CONSTRAINT ck_rental_contracts_status CHECK (status IN ('DRAFT', 'ACTIVE', 'ENDED', 'CANCELLED'))
);

CREATE TABLE contract_tenants (
    contract_id BIGINT NOT NULL REFERENCES rental_contracts(id) ON DELETE RESTRICT,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    primary_tenant BOOLEAN NOT NULL DEFAULT FALSE,
    move_in_date DATE,
    move_out_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (contract_id, tenant_id),
    CONSTRAINT ck_contract_tenants_dates CHECK (move_out_date IS NULL OR move_in_date IS NULL OR move_out_date >= move_in_date)
);

CREATE TABLE utility_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE RESTRICT,
    billing_year INTEGER NOT NULL,
    billing_month INTEGER NOT NULL,
    electricity_old_reading NUMERIC(12, 2) NOT NULL DEFAULT 0,
    electricity_new_reading NUMERIC(12, 2) NOT NULL DEFAULT 0,
    electricity_unit_price NUMERIC(15, 2) NOT NULL DEFAULT 0,
    water_old_reading NUMERIC(12, 2) NOT NULL DEFAULT 0,
    water_new_reading NUMERIC(12, 2) NOT NULL DEFAULT 0,
    water_unit_price NUMERIC(15, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_utility_readings_month CHECK (billing_month BETWEEN 1 AND 12),
    CONSTRAINT ck_utility_readings_electricity CHECK (electricity_new_reading >= electricity_old_reading),
    CONSTRAINT ck_utility_readings_water CHECK (water_new_reading >= water_old_reading),
    CONSTRAINT ck_utility_readings_prices CHECK (electricity_unit_price >= 0 AND water_unit_price >= 0)
);

CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL REFERENCES rental_contracts(id) ON DELETE RESTRICT,
    invoice_number VARCHAR(50) NOT NULL UNIQUE,
    billing_year INTEGER NOT NULL,
    billing_month INTEGER NOT NULL,
    issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
    due_date DATE NOT NULL,
    subtotal NUMERIC(15, 2) NOT NULL DEFAULT 0,
    discount_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    paid_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_invoices_month CHECK (billing_month BETWEEN 1 AND 12),
    CONSTRAINT ck_invoices_amounts CHECK (
        subtotal >= 0
        AND discount_amount >= 0
        AND total_amount >= 0
        AND paid_amount >= 0
        AND paid_amount <= total_amount
    ),
    CONSTRAINT ck_invoices_status CHECK (status IN ('DRAFT', 'UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED'))
);

ALTER TABLE utility_readings
    ADD COLUMN invoice_id BIGINT REFERENCES invoices(id) ON DELETE SET NULL;

CREATE TABLE invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    item_type VARCHAR(30) NOT NULL,
    description VARCHAR(255) NOT NULL,
    quantity NUMERIC(12, 2) NOT NULL,
    unit_price NUMERIC(15, 2) NOT NULL,
    amount NUMERIC(15, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_invoice_items_type CHECK (item_type IN ('RENT', 'ELECTRICITY', 'WATER', 'SERVICE', 'OTHER')),
    CONSTRAINT ck_invoice_items_amounts CHECK (quantity > 0 AND unit_price >= 0 AND amount >= 0)
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id) ON DELETE RESTRICT,
    amount NUMERIC(15, 2) NOT NULL,
    paid_at TIMESTAMPTZ NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    payment_status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    transaction_reference VARCHAR(100),
    note TEXT,
    received_by BIGINT REFERENCES user_accounts(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_payments_amount CHECK (amount > 0),
    CONSTRAINT ck_payments_method CHECK (payment_method IN ('CASH', 'BANK_TRANSFER', 'CARD', 'OTHER')),
    CONSTRAINT ck_payments_status CHECK (payment_status IN ('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED'))
);

CREATE TABLE maintenance_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE RESTRICT,
    tenant_id BIGINT REFERENCES tenants(id) ON DELETE RESTRICT,
    created_by BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE RESTRICT,
    assigned_to BIGINT REFERENCES user_accounts(id) ON DELETE RESTRICT,
    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    resolution_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_maintenance_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    CONSTRAINT ck_maintenance_status CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))
);

CREATE INDEX idx_user_accounts_status ON user_accounts(status);
CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);
CREATE INDEX idx_user_roles_role_id ON user_roles(role_id);

CREATE INDEX idx_properties_landlord_id ON properties(landlord_id);
CREATE INDEX idx_properties_status ON properties(status);

CREATE INDEX idx_rooms_property_id ON rooms(property_id);
CREATE INDEX idx_rooms_status ON rooms(status);
CREATE UNIQUE INDEX uk_rooms_property_room_number_active ON rooms(property_id, lower(room_number)) WHERE deleted_at IS NULL;

CREATE INDEX idx_tenants_landlord_id ON tenants(landlord_id);
CREATE INDEX idx_tenants_user_account_id ON tenants(user_account_id);
CREATE INDEX idx_tenants_status ON tenants(status);
CREATE UNIQUE INDEX uk_tenants_landlord_identity_active ON tenants(landlord_id, identity_number) WHERE deleted_at IS NULL AND identity_number IS NOT NULL;

CREATE INDEX idx_rental_contracts_room_id ON rental_contracts(room_id);
CREATE INDEX idx_rental_contracts_status ON rental_contracts(status);
CREATE INDEX idx_rental_contracts_start_date ON rental_contracts(start_date);
CREATE INDEX idx_rental_contracts_end_date ON rental_contracts(end_date);
CREATE UNIQUE INDEX uk_rental_contracts_active_room ON rental_contracts(room_id) WHERE status = 'ACTIVE' AND deleted_at IS NULL;

CREATE INDEX idx_contract_tenants_contract_id ON contract_tenants(contract_id);
CREATE INDEX idx_contract_tenants_tenant_id ON contract_tenants(tenant_id);
CREATE UNIQUE INDEX uk_contract_tenants_primary ON contract_tenants(contract_id) WHERE primary_tenant = TRUE;

CREATE INDEX idx_utility_readings_room_id ON utility_readings(room_id);
CREATE UNIQUE INDEX uk_utility_readings_room_period_active ON utility_readings(room_id, billing_year, billing_month) WHERE deleted_at IS NULL;

CREATE INDEX idx_invoices_contract_id ON invoices(contract_id);
CREATE INDEX idx_invoices_status ON invoices(status);
CREATE INDEX idx_invoices_due_date ON invoices(due_date);
CREATE UNIQUE INDEX uk_invoices_contract_period_active ON invoices(contract_id, billing_year, billing_month) WHERE deleted_at IS NULL;

CREATE INDEX idx_invoice_items_invoice_id ON invoice_items(invoice_id);
CREATE INDEX idx_invoice_items_item_type ON invoice_items(item_type);

CREATE INDEX idx_payments_invoice_id ON payments(invoice_id);
CREATE INDEX idx_payments_status ON payments(payment_status);
CREATE INDEX idx_payments_paid_at ON payments(paid_at);
CREATE UNIQUE INDEX uk_payments_transaction_reference ON payments(transaction_reference) WHERE transaction_reference IS NOT NULL;

CREATE INDEX idx_maintenance_room_id ON maintenance_requests(room_id);
CREATE INDEX idx_maintenance_tenant_id ON maintenance_requests(tenant_id);
CREATE INDEX idx_maintenance_created_by ON maintenance_requests(created_by);
CREATE INDEX idx_maintenance_assigned_to ON maintenance_requests(assigned_to);
CREATE INDEX idx_maintenance_status ON maintenance_requests(status);
CREATE INDEX idx_maintenance_priority ON maintenance_requests(priority);
CREATE INDEX idx_maintenance_submitted_at ON maintenance_requests(submitted_at);

INSERT INTO roles(name, description)
VALUES
    ('ADMIN', 'System administrator'),
    ('LANDLORD', 'Property owner or manager'),
    ('TENANT', 'Room tenant')
ON CONFLICT (name) DO NOTHING;
