CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(30) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uk_roles_name UNIQUE (name),
    CONSTRAINT ck_roles_name_uppercase
        CHECK (name = UPPER(name))
);

INSERT INTO roles (name, description)
VALUES
    ('ADMIN', 'Quản trị viên hệ thống'),
    ('LANDLORD', 'Chủ trọ'),
    ('TENANT', 'Người thuê');