CREATE TABLE refresh_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE RESTRICT,
    token_hash VARCHAR(64) NOT NULL,
    family_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    replaced_by_session_id BIGINT REFERENCES refresh_sessions(id) ON DELETE SET NULL,
    CONSTRAINT uk_refresh_sessions_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_refresh_sessions_expiration CHECK (expires_at > created_at),
    CONSTRAINT ck_refresh_sessions_last_used CHECK (last_used_at IS NULL OR last_used_at >= created_at),
    CONSTRAINT ck_refresh_sessions_revoked CHECK (revoked_at IS NULL OR revoked_at >= created_at),
    CONSTRAINT ck_refresh_sessions_not_self_replaced CHECK (replaced_by_session_id IS NULL OR replaced_by_session_id <> id)
);

CREATE INDEX idx_refresh_sessions_user_account_id ON refresh_sessions(user_account_id);
CREATE INDEX idx_refresh_sessions_family_id ON refresh_sessions(family_id);
CREATE INDEX idx_refresh_sessions_active_expiration ON refresh_sessions(expires_at) WHERE revoked_at IS NULL;
CREATE INDEX idx_refresh_sessions_user_active ON refresh_sessions(user_account_id, expires_at) WHERE revoked_at IS NULL;
